require_relative "board"
require_relative "pieces"
require_relative 'bishop'
require_relative "king"
require_relative "knight"
require_relative "pawn"
require_relative "queen"
require_relative "rook"
require_relative "display"
